[book]
authors = ["David Lawrence Campbell"]
description = "Personal website."
language = "en"
multilingual = false
src = "src"
title = "David Lawrence Campbell"

[output.html]
git-repository-url = "https://github.com/dcampbell24/dlc-name"
additional-css = ["custom.css"]

[preprocessor.djot]
